services:
  db:
    image: postgres:17
    container_name: my-project-db
    environment:
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: "Test"

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: